[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "function"

[tool.black]
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | data
  | .venv
  | migrations
)
'''

[tool.isort]
profile = "black"
py_version = 312
skip_gitignore = true